config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions',
   :passwords => 'users/passwords'
  }
  resources :users do
    resource :relationships, only:[:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :books do
  	resource :favorites
  	resource :book_comments
  end
  root 'home#top'
  # get 'home#about'
  get "home/about" => "home#about"

  # get '/search', to: 'searchs#search'
  get '/search' => 'search#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	has_many :book_comments, dependent: :destroy
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name: "User"
	belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable
  has_many :books
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end
  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction,  length: { maximum: 50 }
  attachment :profile_image, destroy: false

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :authenticate_user!

  def show
    @book = Book.find(params[:id])
    @books = Book.new
    @user = User.find(@book.user_id)
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
    # @bookers = Book.find(params[:id])
    book = Book.new
    @users=User.all
    # @user = User.find(params[:id])
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。

    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to book_path(@book.id), notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
      flash[:notice]= "error"
      @books=Book.all
      render :index
  	end
  end

  def edit
  	@book = Book.find(params[:id])
    if @book.user_id != current_user.id

      redirect_to books_path
    end
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
	def show
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def update
   contact = Contact.find(params[:id]) #contact_mailer.rbの引数を指定
   contact.update(contact_params)
   user = contact.user
   ContactMailer.send_when_admin_reply(user, contact).deliver
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		@book = Book.find(params[:book_id])
        @favorite = current_user.favorites.new(book_id: @book.id)
        @favorite.save
	end

	def destroy
		@book = Book.find(params[:book_id])
        @favorite = current_user.favorites.find_by(book_id: @book.id)
        @favorite.destroy
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params["search"]["model"]
    @content = params["search"]["content"]
    @method = params["search"]["method"]
    @records = search_for(@model, @content, @method)
    @book = Book.new
  end

  private
  def search_for(model, content, method)
    if model == 'user'
      if method == 'perfect'
        User.where(name:content)
      elsif method == 'forward'
        User.where('name LIKE ?', content+'%')
      elsif method == 'backward'
        User.where('name LIKE ?', '%'+content)
      else
        User.where('name LIKE ?', '%'+content+'%')
      end
    elsif model == 'book'
      if method == 'perfect'
        Book.where(title:content)
      elsif method == 'forward'
        Book.where('title LIKE ?', content+'%')
      elsif method == 'backward'
        Book.where('title LIKE ?', '%'+content)
      else
        Book.where('title LIKE ?', '%'+content+'%')
      end
    end
  end
end



# class SearchController < ApplicationController
#   before_action :authenticate_user!

# def search
#     if params[:content].present?
#       @books = Product.where('title LIKE ?', "%#{params[:content]}%")
#     else
#       @users = User.where('name LIKE ?', "%#{params[:content]}%")
#     end
#   end
# end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :baria_user, only: [:update]
  before_action :authenticate_user!

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
    if @user.id != current_user.id
    redirect_to user_path(current_user)
    end
  end

  def update
  	@user = User.find(params[:id])
  if @user.update(user_params)
  		redirect_to user_path(@user.id), notice: "successfully updated user!"
  	else
  		render :edit, notice: "error"
  	end
  end

  def follows
    user = User.find(params[:id])
    # @active_relationships = @user.active_relationships
    # @users = @active_relationships.user
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image, :user_id)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_comment.html.erb

<%= form_with url: book_book_comments_path(book), model:[book, book_comment], data: {remote: true} do |f| %>
	<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
	<%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

<% if book.user == current_user %>
	<td><%= link_to "Edit",edit_book_path(book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
	<td><%= link_to "Destroy",book_path(book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
<% end %>

app/views/books/_favorite.html.erb

<% if book.favorited_by?(current_user) %>

 	<%= link_to book_favorites_path(book), method: :delete, remote: true do %>
 	<script src="https://kit.fontawesome.com/8bffd370f9.js" crossorigin="anonymous"></script>
 		<i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
 		<%= book.favorites.count %> いいね
 	<% end %>

<% else %>
 	<%= link_to book_favorites_path(book), method: :post, remote: true do %>
 	<script src="https://kit.fontawesome.com/8bffd370f9.js" crossorigin="anonymous"></script>
 		<i class="fa fa-heart-o" aria-hidden="true"></i>
 		<%= book.favorites.count %> いいね
 	<% end %>
<% end %>

app/views/books/_newform.html.erb
<h2>New book</h2>

<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :Opinion %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit "Create Book", class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="body-wrap">
  <div id="st-container" class="st-container">
    <div class="st-pusher">
      <div class="st-content">
        <div class="st-content-inner">
          <section class="slice slice-lg sct-color-1">
            <div class="container">
              <div class="row">
                <div class="col-md-4 col-md-offset-4">
                  <div class="form-user style-1 rounded has-shadow-1"> 
                    <div class="form-header text-center">
                      <h2 class="form-header-title">Editing Book</h2>
                    </div>

                    <div class="form-body">

                      <!-- ここにform_forを追加します -->
                      <%= form_for(@book) do |f| %>
                        <div class="form-group has-icon">
                          <label class="control-label sr-only" for="inputEmail">Name</label>
                          <div>Title</div>
                          <%= f.text_field :title %>
                          <div>Opinion</div>
                          <%= f.text_field :body %>
                          <%=link_to "Show", book_path(@book) %>
                          <%=link_to"Back", books_path %>
                          <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
                        </div>

                        <%= f.submit "Update Book", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
                      <% end %>
                      <% if @book.errors.any? %>
                        <div id="error_explanation" class="alert alert-danger">
                          <p>error</p>
                          <ul>
                            <% @book.errors.full_messages.each do |message| %>
                              <li><%= message %></li>
                            <% end %>
                          </ul>
                          <div class="container">
                            <div class="row">
                              <% if flash[:notice] %>
                                <%= flash[:notice] %>
                              <% end %>
                            </div>
                          </div>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
	<div class="col-xs-3">
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>

						<%= attachment_image_tag book.user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "100x100" %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book.id) %></td>
					<td><%= book.body %></td>
					<td class="book_<%= book.id %>"><%= render 'books/favorite', book: book %></td>
					<td><%= link_to "#{book.book_comments.count}コメント", book_path(book.id) %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
	<div class="col-xs-3">
		<%= render 'users/profile',user: @user %>
		<%= render 'books/newform',book: @books %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						 <%= link_to user_path(@book.user) do %>
                         <%= attachment_image_tag @book.user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "100x100" %>
                         <%= @book.user.name %>
                         <% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>

					<td>
					<!--favorited_by? 追加-->
					<%= render 'books/favorite', book: @book %>

					<td>
					    <%= @book.book_comments.count %> コメント
				    </td>
				    <td>
				    	<% @book_comments.each do |book_comment| %>
				    </td>
				    <tr>

                       <td><%= book_comment.comment %></td>

                       <% if book_comment.user == current_user %>
					   <td><%= button_to "Destroy",book_book_comments_path(@book.id), {method: :delete, remote: true, class: "btn-sm btn-danger destroy_book_#{@book.id}",params:{comment_id: book_comment.id}} %></td>
				       <% end %>

                    </tr>
                    <% end %>

                  <%= render 'books/book_comment', book: @book, book_comment: @book_comment %>

				</tr>
			</table>

	</div>

app/views/favorites/_favorite.html.erb

<% if book.favorited_by?(current_user) %>

 	<%= link_to book_favorites_path(book), method: :delete, remote: true do %>
 	<script src="https://kit.fontawesome.com/8bffd370f9.js" crossorigin="anonymous"></script>
 		<i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
 		<%= book.favorites.count %> いいね
 	<% end %>

<% else %>
 	<%= link_to book_favorites_path(book), method: :post, remote: true do %>
 	<script src="https://kit.fontawesome.com/8bffd370f9.js" crossorigin="anonymous"></script>
 		<i class="fa fa-heart-o" aria-hidden="true"></i>
 		<%= book.favorites.count %> いいね
 	<% end %>
<% end %>

app/views/favorites/create.js.erb
if (location.pathname == '/books') {
  $(".book_<%= @book.id %>").html("<%= j(render 'books/favorite',  book: @book ) %>")
} else {
  $(".book_<%= @book.id %>").html("<%= j(render 'books/favorite',  book: @book ) %>")
}

app/views/favorites/destroy.js.erb
if (location.pathname == '/books') {
  $(".book_<%= @book.id %>").html("<%= j(render 'favorites/favorite',  book: @book ) %>")
} else {
  $(".book_<%= @book.id %>").html("<%= j(render 'favorites/favorite',  book: @book ) %>")
}